var courses = [
  {
    id: 'WEB001',
    category: 'Web Design & Development',
    name: 'Front End Development',
    instructor: 'Jhankar Mahboob',
    img:
      'https://www.ecribe.com/wp-content/uploads/2020/08/Phero-front-end-development.png',
    price: 80,
  },
  {
    id: 'WEB002',
    category: 'Programing Language',
    name: 'React Js',
    instructor: 'Jordan Walke',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/Reactjs.png',
    price: 500,
  },
  {
    id: 'WEB003',
    category: 'Programing Language',
    name: ' The Complete 2020 Web Development Bootcamp',
    instructor: 'Dr. Angela Yu',
    img:
      'https://www.ecribe.com/wp-content/uploads/2020/08/Web-development.jpg',
    price: 148,
  },
  {
    id: 'WEB004',
    category: 'Design',
    name: 'Adobe Photoshop',
    instructor: 'Imran Ali Dina',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/Photoshop.png',
    price: 80,
  },
  {
    id: 'WEB005',
    category: 'Design',
    name: 'Adobe Premiere Pro',
    instructor: 'Umesh Dinda',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/Premeir-pro.png',
    price: 99,
  },
  {
    id: 'WEB006',
    category: 'Programing Language',
    name: 'Python Development',
    instructor: 'Rafeh Qazi',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/python.jpeg',
    price: 350,
  },
  {
    id: 'WEB007',
    category: 'Programing Language',
    name: 'JavaScript Development',
    instructor: 'Tamim Shahriar Subeen',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/Javascript.png',
    price: 100,
  },
  {
    id: 'WEB008',
    category: 'Programing Language',
    name: 'Node.js API Masterclass With Express & MongoDB',
    instructor: 'Brad Traversy',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/node-js.png',
    price: 200,
  },
  {
    id: 'WEB009',
    category: 'Programing Language',
    name: 'Master Laravel with GraphQL, Vue.js and Tailwind',
    instructor: 'Piotr Jura',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/laravel.png',
    price: 200,
  },
  {
    id: 'WEB010',
    category: 'Search Engine',
    name: 'Complete SEO Training ',
    instructor: 'Peter Kent',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/Seo.jpg',
    price: 48.98,
  },
  {
    id: 'WEB011',
    category: 'Design',
    name: 'Adobe XD UI UX Design',
    instructor: 'Daniel Walter Scott',
    img:
      'https://www.ecribe.com/wp-content/uploads/2020/08/1_LIAu1pZIZABu049UI-_L3Q.jpeg',
    price: 48.98,
  },
  {
    id: 'WEV012',
    category: 'Social Media',
    name: 'Digital Marketing Masterclass',
    instructor: 'Phil Ebiner',
    img:
      'https://www.ecribe.com/wp-content/uploads/2020/08/Digital-Marketing.jpg',
    price: 50,
  },
  {
    id: 'WEV013',
    category: 'Creative',
    name: 'Photography Masterclass',
    instructor: 'William Carnahan',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/Photography.jpg',
    price: 200,
  },
  {
    id: 'WEV014',
    category: 'Programing Language',
    name: 'Object Oriented PHP & MVC',
    instructor: 'Brad Traversy',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/php.jpg',
    price: 100,
  },
  {
    id: 'WEV001',
    category: 'Programing Language',
    name: 'Learn To Create WordPress Themes ',
    instructor: 'Samy Eduonix',
    img: 'https://www.ecribe.com/wp-content/uploads/2020/08/word-press.jpg ',
    price: 30,
  },
];
export default courses;
